/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.EquipamentoVO;
import servicos.EquipamentoServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Fabio
 */
public class UiAlterarEquipamento extends javax.swing.JInternalFrame {

     DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código", "Nome", "Número de série","Patrimônio","Descrição", "Marca","Tecnologia"});
    /**
     * Creates new form UiAlterarEquipamento
     */
    public UiAlterarEquipamento() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableEquipamento = new javax.swing.JTable();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        tlCodigo = new javax.swing.JLabel();
        ltNome = new javax.swing.JLabel();
        jlNumSerie = new javax.swing.JLabel();
        jlPatrimonio = new javax.swing.JLabel();
        jlDesscricao = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jlTeconologia = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jtNumSerie = new javax.swing.JTextField();
        jtPatrimonio = new javax.swing.JTextField();
        jtDescricao = new javax.swing.JTextField();
        jtMarca = new javax.swing.JTextField();
        jtTecnologia = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jbConfirma = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alterar Equipamento");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtableEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Patrimônio"
            }
        ));
        jtableEquipamento.getTableHeader().setReorderingAllowed(false);
        jtableEquipamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableEquipamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableEquipamento);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tlCodigo.setText("Codigo");

        ltNome.setText("Nome");

        jlNumSerie.setText("Número de série ");

        jlPatrimonio.setText("Patrimônio");

        jlDesscricao.setText("Descrição");

        jlMarca.setText("Marca");

        jlTeconologia.setText("Tecnologia");

        jtCodigo.setEditable(false);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNumSerie)
                            .addComponent(jlPatrimonio))
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNumSerie))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jtPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(ltNome)
                    .addComponent(tlCodigo))
                .addGap(59, 59, 59)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDesscricao)
                    .addComponent(jlMarca)
                    .addComponent(jlTeconologia))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jtMarca)
                    .addComponent(jtTecnologia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(tlCodigo))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ltNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNumSerie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 19, Short.MAX_VALUE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDesscricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMarca))
                        .addGap(39, 39, 39)))
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPatrimonio)
                    .addComponent(jtPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTeconologia)
                    .addComponent(jtTecnologia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jLayeredPane2.setLayer(tlCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ltNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlNumSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlPatrimonio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlDesscricao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlTeconologia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtNumSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtPatrimonio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtDescricao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtTecnologia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbConfirma.setText("Confiirmar");
        jbConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmaActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jbConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jLayeredPane3.setLayer(jbConfirma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane3))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
     private void limparCampos(){
            jtCodigo.setText(null);
            jtNome.setText(null);
            jtNumSerie.setText(null);
            jtPatrimonio.setText(null);
            jtDescricao.setText(null);
            jtMarca.setText(null);
            jtTecnologia.setText(null);                 
        }// fecha limpar 
        
    private void confirmarAlteracao(){
            int linha = jtableEquipamento.getSelectedRow();
        
            if(linha == -1){
                JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
                return;
            }
            try {
            EquipamentoVO eVO = new EquipamentoVO();
            eVO.setIdEquipamento(Long.parseLong(jtCodigo.getText()));
            if (jtNome.getText().isEmpty()) {
                    throw  new NumberFormatException("Preencha o nome");
                }else{
                    eVO.setNomeEquipamento(jtNome.getText());
            }
            if (jtNumSerie.getText().isEmpty()) {
                throw new NumberFormatException("Preencha o número de série");
            }else{
                eVO.setNumSerie(Integer.parseInt(jtNumSerie.getText()));
            }
            if (jtPatrimonio.getText().isEmpty()) {
                    throw new NumberFormatException("Preencha o patrimonio");
            } else {
                eVO.setPatrimonio(jtPatrimonio.getText());
            }
            if (jtDescricao.getText().isEmpty()) {
                throw new NumberFormatException("Preencha a descrção");
            } else {
                eVO.setDescricao(jtDescricao.getText());
            }
            if (jtMarca.getText().isEmpty()) {
                throw new NumberFormatException("Preencha campo marca");
            } else {
                eVO.setMarca(jtMarca.getText());
            }
            if (jtTecnologia.getText().isEmpty()) {
                throw new NumberFormatException("Preencha o campo tecnologia ");
            } else {
                eVO.setTecnologio(jtTecnologia.getText());
            }
                
                EquipamentoServicos es = ServicosFactory.getEquipamentoServicos();
                es.alterarEquipamento(eVO);
                
                JOptionPane.showMessageDialog(rootPane,
                        "Produto alterado com sucesso!! ");                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,
                    "Erro ao alterar!! "+e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            }
        }//fechaa confirmaralteracao
        
    private void alterar(){
            int linha = jtableEquipamento.getSelectedRow();

            if(linha == -1){
                JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
                return;
            }
            jtCodigo.setText(jtableEquipamento.getValueAt(linha, 0).toString());
            jtNome.setText(jtableEquipamento.getValueAt(linha, 1).toString());
            jtNumSerie.setText(jtableEquipamento.getValueAt(linha, 2).toString());
            jtPatrimonio.setText(jtableEquipamento.getValueAt(linha, 3).toString());            
            jtDescricao.setText(jtableEquipamento.getValueAt(linha, 4).toString());
            jtMarca.setText(jtableEquipamento.getValueAt(linha, 5).toString());
            jtTecnologia.setText(jtableEquipamento.getValueAt(linha, 6).toString());
            
        }//fecha alterar
    
    private void limparTabela(){
        dtm.setNumRows(0);
        
       // jtDetalhe.setText(null);
        
    }//limpar table 
        
    private void  preencherTabela(){
        try {
            
            EquipamentoServicos es = ServicosFactory.getEquipamentoServicos();
            ArrayList<EquipamentoVO> eq = es.buscarEquipamento();
            
            for (int i = 0; i < eq.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(eq.get(i).getIdEquipamento()),
                    eq.get(i).getNomeEquipamento(),
                    String.valueOf(eq.get(i).getNumSerie()),
                    eq.get(i).getPatrimonio(),
                    eq.get(i).getDescricao(),
                    eq.get(i).getMarca(),
                    eq.get(i).getTecnologio()
                });
            }
            jtableEquipamento.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    "Erro ao buscar",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//fecha peencher tabela
    
    private void verificarEquipamentoSelecionado(){
        try {
            int linha = jtableEquipamento.getSelectedRow();
            
            if (linha == -1) {
                JOptionPane.showMessageDialog(this, 
                        "Selecione uma Linha !! ");
            } else {
                
                String id = (String) jtableEquipamento.getValueAt(linha, 0);
                String query = "where idequipamento = "+id;
                
                EquipamentoServicos es = ServicosFactory.getEquipamentoServicos();
                ArrayList<EquipamentoVO> eq = es.filtrar(query);
                
               /*
                * for (int i = 0; i < eq.size(); i++) {
                *   jtDetalhe.setText(
                *            eq.get(i).toString());
                * }
                */
                jtableEquipamento.setModel(dtm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro!! "+e.getMessage());
        }//FECHA CATCH
    }//fecha verificar

    private void jtableEquipamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableEquipamentoMouseClicked
        verificarEquipamentoSelecionado();
        alterar();
    }//GEN-LAST:event_jtableEquipamentoMouseClicked

    private void jbConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmaActionPerformed
        confirmarAlteracao();
        limparTabela();
        preencherTabela();
        limparCampos();
    }//GEN-LAST:event_jbConfirmaActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparCampos();        
    }//GEN-LAST:event_jbLimparActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbConfirma;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlDesscricao;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlNumSerie;
    private javax.swing.JLabel jlPatrimonio;
    private javax.swing.JLabel jlTeconologia;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtDescricao;
    private javax.swing.JTextField jtMarca;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumSerie;
    private javax.swing.JTextField jtPatrimonio;
    private javax.swing.JTextField jtTecnologia;
    private javax.swing.JTable jtableEquipamento;
    private javax.swing.JLabel ltNome;
    private javax.swing.JLabel tlCodigo;
    // End of variables declaration//GEN-END:variables
}
