/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ServidorVO;
import servicos.ServicosFactory;
import servicos.ServidorServicos;

/**
 *
 * @author Fabio
 */
public class UiAlterarServidor extends javax.swing.JInternalFrame {
    
        DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código", "Nome", "CPF","Mátricula","E-mail","Setor","Cargo","Supervisor","Especialização", "Admissão"});
    /**
     * Creates new form UiAlterarServidor
     */
    public UiAlterarServidor() {
        initComponents();
        
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelaServidor = new javax.swing.JTable();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jlCodigo = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jlmatricula = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlSetor = new javax.swing.JLabel();
        jlCargo = new javax.swing.JLabel();
        jlEspecializacao = new javax.swing.JLabel();
        jlSupervisor = new javax.swing.JLabel();
        jlAdmissao = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jtCpf = new javax.swing.JTextField();
        jtMatricula = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jtSetor = new javax.swing.JTextField();
        jtCargo = new javax.swing.JTextField();
        jtEspecializacao = new javax.swing.JTextField();
        jtSupervisor = new javax.swing.JTextField();
        jtAdmissao = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jbAlterar = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Alterar Dados");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtabelaServidor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Mátricula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabelaServidor.getTableHeader().setReorderingAllowed(false);
        jtabelaServidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelaServidorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabelaServidor);
        if (jtabelaServidor.getColumnModel().getColumnCount() > 0) {
            jtabelaServidor.getColumnModel().getColumn(0).setResizable(false);
            jtabelaServidor.getColumnModel().getColumn(1).setResizable(false);
            jtabelaServidor.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlCodigo.setText("Código");

        jlNome.setText("Nome");

        jlCpf.setText("CPF");

        jlmatricula.setText("Mátricula");

        jlEmail.setText("E-mail");

        jlSetor.setText("Setor");

        jlCargo.setText("Cargo");

        jlEspecializacao.setText("Especialização");

        jlSupervisor.setText("Supervisor");

        jlAdmissao.setText("Admissão");

        jtCodigo.setEditable(false);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(393, 393, 393))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigo)
                            .addComponent(jlCpf)
                            .addComponent(jlmatricula)
                            .addComponent(jlEmail))
                        .addGap(30, 30, 30)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(jtNome)
                            .addComponent(jtCpf)
                            .addComponent(jtMatricula)
                            .addComponent(jtEmail))
                        .addGap(103, 103, 103)))
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEspecializacao)
                    .addComponent(jlSupervisor)
                    .addComponent(jlAdmissao)
                    .addComponent(jlCargo)
                    .addComponent(jlSetor))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtSetor)
                    .addComponent(jtCargo)
                    .addComponent(jtEspecializacao)
                    .addComponent(jtSupervisor)
                    .addComponent(jtAdmissao, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSetor))
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jlNome)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCargo)
                            .addComponent(jtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCpf)
                            .addComponent(jlEspecializacao)))
                    .addComponent(jtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jtEspecializacao))
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jlSupervisor))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlmatricula)
                                .addComponent(jtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlEmail)
                            .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jlAdmissao))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jlCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlmatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlSetor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlCargo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlEspecializacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlSupervisor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlAdmissao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtSetor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtCargo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtEspecializacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtSupervisor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtAdmissao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbConfirmar.setText("Confirmar");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jLayeredPane3.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbConfirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterar(){
        int linha = jtabelaServidor.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
            return;
        }
        jtCodigo.setText(jtabelaServidor.getValueAt(linha, 0).toString());
        jtNome.setText(jtabelaServidor.getValueAt(linha, 1).toString());
        jtCpf.setText(jtabelaServidor.getValueAt(linha, 2).toString());
        jtMatricula.setText(jtabelaServidor.getValueAt(linha, 3).toString());
        jtEmail.setText(jtabelaServidor.getValueAt(linha, 4).toString());
        jtSetor.setText(jtabelaServidor.getValueAt(linha, 5).toString());
        jtCargo.setText(jtabelaServidor.getValueAt(linha, 6).toString());
        jtSupervisor.setText(jtabelaServidor.getValueAt(linha, 7).toString());
        jtEspecializacao.setText(jtabelaServidor.getValueAt(linha, 8).toString());
        jtAdmissao.setText(jtabelaServidor.getValueAt(linha, 9).toString());
        
        
    }//fecha alterar
        
    private void confirmarAlteracao(){
        int linha = jtabelaServidor.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
            return;
        }
        try {
            ServidorVO sVO = new ServidorVO();
            sVO.setIdServidor(Long.parseLong(jtCodigo.getText()));
            if (jtNome.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Nome");
            } else {
             sVO.setNomeServidor(jtNome.getText());   
            }            
            if (jtCpf.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo CPF");
            } else {
                sVO.setCpf(Long.parseLong(jtCpf.getText()));
            }
            if (jtMatricula.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Mátricula");
            } else {
                sVO.setMatricula(Long.parseLong(jtMatricula.getText()));
            }          
            if (jtEmail.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo E-mail");
            } else {
                sVO.setEmail(jtEmail.getText());
            }
            if (jtSetor.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Setor");
            } else {
                sVO.setSetor(jtSetor.getText());
            }
            if (jtCargo.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Cargo");
            } else {
                sVO.setCargo(jtCargo.getText());
            }
            if (jtSupervisor.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Supervisor");
            } else {
                sVO.setSupervisor(jtSupervisor.getText());
            }
            if (jtEspecializacao.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Especialização");
            } else {
                sVO.setEspecializacao(jtEspecializacao.getText());
            }
            if (jtAdmissao.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Admissão");
            } else {
            sVO.setAdmissao(jtAdmissao.getText());
            }
            
            ServidorServicos ss = ServicosFactory.getServidorServicos(); 
            ss.alterarServidor(sVO);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Servidor alterado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro! "+e.getMessage());
        }//fecha catch
    }//fecha confirmarAlteracao 
    
    private void limparCampos(){
        jtCodigo.setText(null);
        jtNome.setText(null);
        jtCpf.setText(null);
        jtEmail.setText(null);
        jtMatricula.setText(null);
        jtSetor.setText(null);
        jtCargo.setText(null);
        jtSupervisor.setText(null);
        jtEspecializacao.setText(null);
        jtAdmissao.setText(null);
    }//fecha limpar
    
    private void preencherTabela(){
        try {
         
            ServidorServicos ss = ServicosFactory.getServidorServicos();
            ArrayList<ServidorVO> serv =  ss.buscarServidor();
            
            for (int i = 0; i < serv.size(); i++) {
                dtm.addRow(new String []{
                    String.valueOf(serv.get(i).getIdServidor()),
                    serv.get(i).getNomeServidor(),
                    String.valueOf(serv.get(i).getCpf()),
                    String.valueOf(serv.get(i).getMatricula()),
                    serv.get(i).getEmail(),
                    serv.get(i).getSetor(),
                    serv.get(i).getCargo(),
                    serv.get(i).getSupervisor(),
                    serv.get(i).getEspecializacao(),
                    serv.get(i).getAdmissao()
                });
            }
            jtabelaServidor.setModel(dtm);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Erro !! "+e.getMessage());
        
        }
    }//feca limpar table
    
    private void verificarServidorSeleconado(){
        try {
            int linha = jtabelaServidor.getSelectedRow();
            
            if (linha == -1) {
                JOptionPane.showMessageDialog(this,
                        "Selecione uma linha! ");
            } else {
                ServidorServicos ss = ServicosFactory.getServidorServicos();
                ArrayList<ServidorVO> serv = new ArrayList<>();
                
                String id = (String) jtabelaServidor.getValueAt(linha, 0);
                String query = "where idservidor = "+id;
                serv = ss.filtrar(query);
            
               /*for (int i = 0; i < serv.size(); i++) {
                        jtDetalhe.setText(
                            serv.get(i).toString());
                }//for*/ 
                
                jtabelaServidor.setModel(dtm);
            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro!! "+e.getMessage());
        }//FECHA CATCH
    }//fecha verificar 
    
    private void limparTabela(){
        dtm.setNumRows(0);
        
    }//limpar table 
        
    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        alterar();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        confirmarAlteracao();
        limparTabela();
        preencherTabela();
        limparCampos();
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jtabelaServidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelaServidorMouseClicked
        verificarServidorSeleconado();
        alterar();
    }//GEN-LAST:event_jtabelaServidorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JLabel jlAdmissao;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEspecializacao;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSetor;
    private javax.swing.JLabel jlSupervisor;
    private javax.swing.JLabel jlmatricula;
    private javax.swing.JTextField jtAdmissao;
    private javax.swing.JTextField jtCargo;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEspecializacao;
    private javax.swing.JTextField jtMatricula;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtSetor;
    private javax.swing.JTextField jtSupervisor;
    private javax.swing.JTable jtabelaServidor;
    // End of variables declaration//GEN-END:variables
}
