/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.ServidorVO;
import servicos.ServicosFactory;
import servicos.ServidorServicos;

/**
 *
 * @author Fábio Guedes
 * @version 1.0 inicial
 * @since 07/06/2018 - 02:30
 */
public class UiCadServidor extends javax.swing.JInternalFrame {

    /**
     * Creates new form UiCadServidor
     */
    public UiCadServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jCpf = new javax.swing.JLabel();
        jlMatricula = new javax.swing.JLabel();
        jlEmeil = new javax.swing.JLabel();
        jlSetor = new javax.swing.JLabel();
        jlCargo = new javax.swing.JLabel();
        jlEspecializacao = new javax.swing.JLabel();
        jlSupervisor = new javax.swing.JLabel();
        jlAdmissao = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtCpf = new javax.swing.JTextField();
        jtMatricula = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jtSetor = new javax.swing.JTextField();
        jtCargo = new javax.swing.JTextField();
        jtEspecializacao = new javax.swing.JTextField();
        jtSupervisor = new javax.swing.JTextField();
        jtAdmissao = new javax.swing.JTextField();
        jlNomeErro = new javax.swing.JLabel();
        jlCpfErro = new javax.swing.JLabel();
        jlMatErro = new javax.swing.JLabel();
        jlEmailErro = new javax.swing.JLabel();
        jlSetorErro = new javax.swing.JLabel();
        jlCargoErro = new javax.swing.JLabel();
        jlEspErro = new javax.swing.JLabel();
        jlSupERro = new javax.swing.JLabel();
        jlAdErro = new javax.swing.JLabel();
        Layerpael = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Servidores");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jCpf.setText("CPF");

        jlMatricula.setText("Mátricula");

        jlEmeil.setText("E-mail");

        jlSetor.setText("Setor");

        jlCargo.setText("Cargo");

        jlEspecializacao.setText("Especialização");

        jlSupervisor.setText("Supervisor");

        jlAdmissao.setText("Admissão");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });

        jtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCpfFocusLost(evt);
            }
        });

        jtMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtMatriculaFocusLost(evt);
            }
        });

        jtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEmailFocusLost(evt);
            }
        });

        jtSetor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtSetorFocusLost(evt);
            }
        });

        jtCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCargoFocusLost(evt);
            }
        });

        jtEspecializacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEspecializacaoFocusLost(evt);
            }
        });

        jtSupervisor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtSupervisorFocusLost(evt);
            }
        });

        jtAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAdmissaoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNome)
                    .addComponent(jlMatricula)
                    .addComponent(jCpf)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlSetor)
                        .addComponent(jlEmeil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlNomeErro, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlCpfErro, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlCargo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtSetor, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jtEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlEmailErro, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                                    .addComponent(jlSetorErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlSupervisor)
                                    .addComponent(jlAdmissao)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlMatErro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlEspecializacao)))
                        .addGap(37, 37, 37)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jtEspecializacao)
                            .addComponent(jtSupervisor)
                            .addComponent(jtAdmissao))))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlCargoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlEspErro, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlSupERro, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                            .addComponent(jlAdErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCargo)
                            .addComponent(jlCargoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCpf)
                            .addComponent(jlCpfErro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlEspecializacao)
                        .addComponent(jtEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlMatricula)
                        .addComponent(jlMatErro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlEspErro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(jtSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSupervisor)
                            .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEmeil)
                            .addComponent(jlEmailErro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlSupERro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlAdErro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlSetorErro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSetor)))
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlAdmissao)
                        .addComponent(jtAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlEmeil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlSetor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlCargo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlEspecializacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlSupervisor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlAdmissao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtSetor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtCargo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtEspecializacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtSupervisor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtAdmissao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlCpfErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlMatErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlEmailErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlSetorErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlCargoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlEspErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlSupERro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlAdErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Layerpael.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Layerpael.setAutoscrolls(true);

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayerpaelLayout = new javax.swing.GroupLayout(Layerpael);
        Layerpael.setLayout(LayerpaelLayout);
        LayerpaelLayout.setHorizontalGroup(
            LayerpaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerpaelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        LayerpaelLayout.setVerticalGroup(
            LayerpaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerpaelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(LayerpaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        Layerpael.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Layerpael.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Layerpael)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLayeredPane1)
                .addGap(18, 18, 18)
                .addComponent(Layerpael, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        try {
            ServidorVO sVO = new ServidorVO();
            if (jtNome.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Nome");
            } else {
             sVO.setNomeServidor(jtNome.getText());   
            }            
            if (jtCpf.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo CPF");
            } else {
                sVO.setCpf(Long.parseLong(jtCpf.getText()));
            }
            if (jtMatricula.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Mátricula");
            } else {
                sVO.setMatricula(Long.parseLong(jtMatricula.getText()));
            }          
            if (jtEmail.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo E-mail");
            } else {
                sVO.setEmail(jtEmail.getText());
            }
            if (jtSetor.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Setor");
            } else {
                sVO.setSetor(jtSetor.getText());
            }
            if (jtCargo.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Cargo");
            } else {
                sVO.setCargo(jtCargo.getText());
            }
            if (jtSupervisor.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Supervisor");
            } else {
                sVO.setSupervisor(jtSupervisor.getText());
            }
            if (jtEspecializacao.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Especialização");
            } else {
                sVO.setEspecializacao(jtEspecializacao.getText());
            }
            if (jtAdmissao.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Admissão");
            } else {
            sVO.setAdmissao(jtAdmissao.getText());
            }
            
            ServidorServicos ss = ServicosFactory.getServidorServicos();            
            ss.cadastrarServidor(sVO);
            
            JOptionPane.showMessageDialog(rootPane,
                    "Cadastrardo com sucesso!! ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch     
    }//fecha cadastrar
    
    private void limpar(){
        jtNome.setText(null);
        jtCpf.setText(null);
        jtEmail.setText(null);
        jtMatricula.setText(null);
        jtSetor.setText(null);
        jtCargo.setText(null);
        jtSupervisor.setText(null);
        jtEspecializacao.setText(null);
        jtAdmissao.setText(null);
    }//fecha limpar
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
       if(jtNome.getText().isEmpty()){
            jtNome.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlNomeErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtNome.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlNomeErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCpfFocusLost
        if(jtCpf.getText().isEmpty()){
            jtCpf.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlCpfErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtCpf.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlCpfErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtCpfFocusLost

    private void jtMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtMatriculaFocusLost
        if(jtMatricula.getText().isEmpty()){
            jtMatricula.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlMatErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtMatricula.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlMatErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtMatriculaFocusLost

    private void jtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEmailFocusLost
        if(jtEmail.getText().isEmpty()){
            jtEmail.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlEmailErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtEmail.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlEmailErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtEmailFocusLost

    private void jtSetorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtSetorFocusLost
        if(jtSetor.getText().isEmpty()){
            jtSetor.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlSetorErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtSetor.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlSetorErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtSetorFocusLost

    private void jtCargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCargoFocusLost
       if(jtCargo.getText().isEmpty()){
            jtCargo.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlCargoErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtCargo.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlCargoErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtCargoFocusLost

    private void jtEspecializacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEspecializacaoFocusLost
        if(jtEspecializacao.getText().isEmpty()){
            jtEspecializacao.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlEspErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtEspecializacao.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlEspErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtEspecializacaoFocusLost

    private void jtSupervisorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtSupervisorFocusLost
        if(jtSupervisor.getText().isEmpty()){
            jtSupervisor.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlSupERro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtSupervisor.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlSupERro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtSupervisorFocusLost

    private void jtAdmissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAdmissaoFocusLost
        if(jtAdmissao.getText().isEmpty()){
            jtAdmissao.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlAdErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtAdmissao.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlAdErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtAdmissaoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Layerpael;
    private javax.swing.JLabel jCpf;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlAdErro;
    private javax.swing.JLabel jlAdmissao;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlCargoErro;
    private javax.swing.JLabel jlCpfErro;
    private javax.swing.JLabel jlEmailErro;
    private javax.swing.JLabel jlEmeil;
    private javax.swing.JLabel jlEspErro;
    private javax.swing.JLabel jlEspecializacao;
    private javax.swing.JLabel jlMatErro;
    private javax.swing.JLabel jlMatricula;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlSetor;
    private javax.swing.JLabel jlSetorErro;
    private javax.swing.JLabel jlSupERro;
    private javax.swing.JLabel jlSupervisor;
    private javax.swing.JTextField jtAdmissao;
    private javax.swing.JTextField jtCargo;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEspecializacao;
    private javax.swing.JTextField jtMatricula;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtSetor;
    private javax.swing.JTextField jtSupervisor;
    // End of variables declaration//GEN-END:variables
}
