/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.ProdutoVO;
import servicos.ProdutoServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Fabio
 */
public class UiCadProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form UiCadProduto
     */
    public UiCadProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlNumSerie = new javax.swing.JLabel();
        jlPatrimonio = new javax.swing.JLabel();
        jlSetor = new javax.swing.JLabel();
        jlDescricao = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jlModelo = new javax.swing.JLabel();
        jlEstadoFisico = new javax.swing.JLabel();
        jlFabricante = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtNumSerie = new javax.swing.JTextField();
        jtPatrimonio = new javax.swing.JTextField();
        jtDescricao = new javax.swing.JTextField();
        jtSetor = new javax.swing.JTextField();
        jtEstadoFisico = new javax.swing.JTextField();
        jtMarca = new javax.swing.JTextField();
        jtFabricante = new javax.swing.JTextField();
        jtModelo = new javax.swing.JTextField();
        jlNomeErro = new javax.swing.JLabel();
        jlNumErro = new javax.swing.JLabel();
        jlPatErro = new javax.swing.JLabel();
        jlSetorErro = new javax.swing.JLabel();
        jlDesccricoErro = new javax.swing.JLabel();
        jlEstadoErro = new javax.swing.JLabel();
        jlMarrcaErro = new javax.swing.JLabel();
        jlModeloErro = new javax.swing.JLabel();
        jlFabricanteErro = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Produto");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jlNumSerie.setText("Número de série");

        jlPatrimonio.setText("Patrimônio");

        jlSetor.setText("Setor designado");

        jlDescricao.setText("Descrição");

        jlMarca.setText("Marca");

        jlModelo.setText("Modelo");

        jlEstadoFisico.setText("Estado físico");

        jlFabricante.setText("Fabricante");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });

        jtNumSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumSerieFocusLost(evt);
            }
        });

        jtPatrimonio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPatrimonioFocusLost(evt);
            }
        });

        jtDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDescricaoFocusLost(evt);
            }
        });

        jtSetor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtSetorFocusLost(evt);
            }
        });

        jtEstadoFisico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEstadoFisicoFocusLost(evt);
            }
        });

        jtMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtMarcaFocusLost(evt);
            }
        });

        jtFabricante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtFabricanteFocusLost(evt);
            }
        });

        jtModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtModeloFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(31, 31, 31)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jlPatrimonio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlDescricao)
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlNumSerie, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jlSetor)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(jtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlSetorErro))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(jtPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlPatErro))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(jtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlNumErro))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlDesccricoErro))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlMarca)
                                    .addComponent(jlEstadoFisico)
                                    .addComponent(jlFabricante)
                                    .addComponent(jlModelo))
                                .addGap(29, 29, 29)))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtEstadoFisico)
                            .addComponent(jtMarca)
                            .addComponent(jtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtFabricante))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNomeErro)
                    .addComponent(jlEstadoErro)
                    .addComponent(jlMarrcaErro)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlModeloErro, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlFabricanteErro)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeErro))
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlEstadoErro)
                        .addGap(71, 71, 71))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEstadoFisico)
                            .addComponent(jtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNumErro)
                            .addComponent(jlNumSerie))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlMarca)
                                    .addComponent(jlMarrcaErro)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlPatErro)
                                    .addComponent(jlPatrimonio))))))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jlModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlSetorErro))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlSetor)
                                    .addComponent(jtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlModeloErro))
                        .addGap(17, 17, 17)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlFabricante)
                        .addComponent(jtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlDescricao)
                        .addComponent(jlDesccricoErro)
                        .addComponent(jlFabricanteErro))
                    .addComponent(jtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlNumSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlPatrimonio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlSetor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlDescricao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlEstadoFisico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlFabricante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtNumSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtPatrimonio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtDescricao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtSetor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtEstadoFisico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtFabricante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlNumErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlPatErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlSetorErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlDesccricoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlEstadoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlMarrcaErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlModeloErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlFabricanteErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jLayeredPane2.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        try {
            ProdutoVO p = new ProdutoVO();
            if (jtNome.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Nome");
            } else {
                p.setNomeProduto(jtNome.getText());
            }
            if (jtNumSerie.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Número de série");
            } else {
                p.setNumSerie(Integer.parseInt(jtNumSerie.getText()));
            }
            if (jtPatrimonio.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo patrimônio");
            } else {
                p.setPatrimonio(jtPatrimonio.getText());
            }
            if (jtSetor.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Setor");
            } else {
                p.setSetor(jtSetor.getText());
            }
            if (jtDescricao.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Descreição");
            } else {
                p.setDescricao(jtDescricao.getText());
            }
            if (jtMarca.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Marca");
            } else {
                p.setMarca(jtMarca.getText());
            }
            if (jtModelo.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Modelo");
            } else {
                p.setModelo(jtModelo.getText());
            }
            if (jtEstadoFisico.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Estado físico");
            } else {
                p.setEstado(jtEstadoFisico.getText());
            }
            if (jtFabricante.getText().isEmpty()) {
                throw  new NumberFormatException("Preencha o campo Fabricante");
            } else {
                p.setFabricante(jtFabricante.getText());
            }
                
            ProdutoServicos ps = ServicosFactory.getProdutoServicos();
            ps.cadastrarProduto(p);
                
            JOptionPane.showMessageDialog(rootPane,
                "Produto cadstrado com sucesso!! ");                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                "Erro ao cadastrar!! "+e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//fechaa cadastrar
        
    private void limpar(){
        jtNome.setText(null);
        jtNumSerie.setText(null);
        jtPatrimonio.setText(null);
        jtSetor.setText(null);
        jtDescricao.setText(null);
        jtMarca.setText(null);
        jtEstadoFisico.setText(null);
        jtModelo.setText(null);
        jtFabricante.setText(null);                 
    }
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if(jtNome.getText().isEmpty()){
            jtNome.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlNomeErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtNome.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlNomeErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtNumSerieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumSerieFocusLost
       if(jtNumSerie.getText().isEmpty()){
            jtNumSerie.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlNumErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtNumSerie.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlNumErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
       }
    }//GEN-LAST:event_jtNumSerieFocusLost

    private void jtEstadoFisicoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEstadoFisicoFocusLost
        if(jtEstadoFisico.getText().isEmpty()){
            jtEstadoFisico.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlEstadoErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtEstadoFisico.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlEstadoErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtEstadoFisicoFocusLost

    private void jtPatrimonioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPatrimonioFocusLost
        if(jtPatrimonio.getText().isEmpty()){
            jtPatrimonio.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlPatErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtPatrimonio.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlPatErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtPatrimonioFocusLost

    private void jtMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtMarcaFocusLost
        if(jtMarca.getText().isEmpty()){
            jtMarca.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlMarrcaErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtMarca.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlMarrcaErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtMarcaFocusLost

    private void jtSetorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtSetorFocusLost
        if(jtSetor.getText().isEmpty()){
            jtSetor.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlSetorErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtSetor.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlSetorErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtSetorFocusLost

    private void jtDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDescricaoFocusLost
        if(jtDescricao.getText().isEmpty()){
            jtDescricao.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlDesccricoErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtDescricao.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlDesccricoErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtDescricaoFocusLost

    private void jtModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtModeloFocusLost
        if(jtModelo.getText().isEmpty()){
            jtModelo.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlModeloErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtModelo.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlModeloErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtModeloFocusLost

    private void jtFabricanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtFabricanteFocusLost
        if(jtFabricante.getText().isEmpty()){
            jtFabricante.setBorder(
                    BorderFactory.createLineBorder(Color.red));
            jlFabricanteErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/exit.png")));
        }else{
            jtFabricante.setBorder(
                    BorderFactory.createLineBorder(Color.gray));
            jlFabricanteErro.setIcon(
                new ImageIcon(getClass().getResource("/icones/accept.png")));
        }
    }//GEN-LAST:event_jtFabricanteFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlDesccricoErro;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlEstadoErro;
    private javax.swing.JLabel jlEstadoFisico;
    private javax.swing.JLabel jlFabricante;
    private javax.swing.JLabel jlFabricanteErro;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlMarrcaErro;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlModeloErro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlNumErro;
    private javax.swing.JLabel jlNumSerie;
    private javax.swing.JLabel jlPatErro;
    private javax.swing.JLabel jlPatrimonio;
    private javax.swing.JLabel jlSetor;
    private javax.swing.JLabel jlSetorErro;
    private javax.swing.JTextField jtDescricao;
    private javax.swing.JTextField jtEstadoFisico;
    private javax.swing.JTextField jtFabricante;
    private javax.swing.JTextField jtMarca;
    private javax.swing.JTextField jtModelo;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumSerie;
    private javax.swing.JTextField jtPatrimonio;
    private javax.swing.JTextField jtSetor;
    // End of variables declaration//GEN-END:variables
}
